# Generated by Django 5.0.6 on 2024-08-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_graph_vertex_edge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertex",
            name="value",
            field=models.IntegerField(),
        ),
    ]
